musicband_app/config/routes.rb
MusicbandApp::Application.routes.draw do

  resources :groupees do
     resources :attendances, :only =>[:create, :destroy]
  end

  resources :performances, :only => [:index, :show, :new, :create]
  resources :contacts, :only => [:index, :create, :destroy]
  resources :songs, :only => [:index, :show]

  resources :blogs do
     resources :comments, :only => [:create, :destroy]
  end

  match 'signup' => "groupees#new"
  match 'login' => "sessions#new"
  match 'sessions' => "sessions#create", :via => :post
  match 'logout' => "sessions#destroy", :via => :delete
  match 'contact' => "contacts#new"
  match 'about' => "public_pages#about"
  root :to => "public_pages#home"

end

musicband_app/app/models/performance.rb
class Performance < ActiveRecord::Base
   has_many :attendances, :foreign_key => "performance_id", :dependent => :destroy
   attr_accessible :name

   def to_param  # overridden
      name
   end
   validates_presence_of :name, :presence => true
end

musicband_app/app/controllers/performances_controller.rb
class PerformancesController < ApplicationController
   respond_to :html

   def index
      @performances = Performance.order("created_at desc")
      respond_with @performances
   end

   def show
      @performance = Performance.find_by_name(params[:id])

      if @performance.nil?
         render "shared/404"
      else
         respond_with @peformance
      end
   end

   def new
      if (!current_groupee.nil? && current_groupee.admin?)
         @performance = Performance.new
      else
         render "shared/403"
      end
   end

   def create
      if (!current_groupee.nil? && current_groupee.admin?)
         @performance = Performance.new(params[:performance])

         if @performance.save
            flash[:success] = "Performance #{@performance.name} successfully created"
            redirect_to performances_path
         else
            render "new"
         end
      else
         render "shared/403"
      end
   end
end

musicband_app/app/views/performances/index.html.erb
<h1 class="colorstyleh1"><center>Peformances</center></h1>
<% if !Performance.find(:all).empty? %>
   <table>
   <% @performances.each do |performance| %>
   <table>
      <div class="entry">
      <tr>
         
            <td><h2 class="colorstyleh2"><%= link_to performance.name, performance %></h2></td>
            <hr />   
      </tr>
      </div>
   </table>
   <% end %>
<% end %>
<br>
<% if (!current_groupee.nil? && current_groupee.admin?) %>
   <%= link_to "New Performance", new_performance_path %>
<% end %>

musicband_app/app/views/performances/new.html.erb
<h1 class="colorstyleh1">New Performance</h1>
<br>
<%= form_for @performance do |form| %>
   <%= render "shared/error_messages", :object => @performance %>
   <table>
      <tr>
         <td><%= form.label :name %></td>
         <td><%= form.text_field :name %></td>
      </tr>
      <tr>
         <td></td>
         <td><%= form.submit %></td>
      </tr>
   </table>
<% end %>

musicband_app/app/views/performances/show.html.erb
<h1 class="colorstyleh1">Performance</h1>
<br>
<div class="entry">
<table>
   <% if !@performance.nil? %>
   <tr>
      <td>Performance name:</td>
      <td><%= @performance.name %></td>
   </tr>
   <% end %>
</table>
</div>
<br>
<h2 class ="colorstyleh2">Groupees Attending</h2>
<br>
<center>
<table border="2" align="center">
   <tr>
      <th class="navaddspace">Username</th>
      <th class="navaddspace">First Name</th>
      <th>Last Name</th>
   </tr>
   <% @performance.attendances.each do |attendance| %>
      <tr>
         <td><%= link_to attendance.groupee.username, groupee_path(attendance.groupee.username)  %></td>
         <td><%= attendance.groupee.first_name %></td>
         <td><%= attendance.groupee.last_name %></td>
      </tr>
   <% end %>
</table>
</center>