musicband_app/config/routes.rb
MusicbandApp::Application.routes.draw do

  resources :groupees do
     resources :attendances, :only =>[:create, :destroy]
  end

  resources :performances, :only => [:index, :show, :new, :create]
  resources :contacts, :only => [:index, :create, :destroy]
  resources :songs, :only => [:index, :show]

  resources :blogs do
     resources :comments, :only => [:create, :destroy]
  end

  match 'signup' => "groupees#new"
  match 'login' => "sessions#new"
  match 'sessions' => "sessions#create", :via => :post
  match 'logout' => "sessions#destroy", :via => :delete
  match 'contact' => "contacts#new"
  match 'about' => "public_pages#about"
  root :to => "public_pages#home"

end

musicband_app/app/models/groupee.rb
class Groupee < ActiveRecord::Base
   has_many :attendances, :foreign_key => "groupee_id", :dependent => :destroy
   has_many :blogs
   has_many :comments
   attr_accessible :first_name, :last_name, :username, :email, :password, :password_confirmation
   has_secure_password

   def to_param  # overridden
      username
   end
   validates :first_name, :presence => true
   validates :last_name, :presence => true
   validates :email, :presence => true
   validates :username, :presence => true, :uniqueness =>{:case_sensitive => false}
   validates :password, :length => {:minimum => 6}
   validates :password_confirmation, :presence => true
end

musicband_app/app/controllers/groupees_controller.rb
class GroupeesController < ApplicationController
   respond_to :html

   #filter finduser is only used with the actions :show, :edit and :update
   before_filter :load_findgroupee, :only => [:show, :edit, :update]

   #Admin Only Function that displays all the current users
   def index
      if (!current_groupee.nil? && current_groupee.admin?)
         @groupees = Groupee.order("created_at desc")
         respond_with @groupees
      else
         render "shared/403"
      end
   end

   #Show is the action that allows a user to see their current page. This action has replaced index 
   def show
      if @groupee.nil?
         render "shared/404"
      else
         if !current_groupee.nil?
            respond_with @groupee
         else
            render "shared/403"
         end
      end
   end

   def new
      @groupee = Groupee.new
   end

      #Create is the action that allows a new user to be added to the database.
   def create
      @groupee = Groupee.new(params[:groupee])

      if @groupee.save
         session[:groupee_id] = @groupee.id
         flash[:success] = "Welcome #{@groupee.username} to MusicBand"
         redirect_to @groupee, :notice => "Groupee Account successfully created." #Changing users to user redirects to a specific user page
      else
         render "new"
      end
   end

   #Edit is the action that allows a user to edit there current profile
   def edit

      #Prevents the current user from editing another users profile
      if current_groupee.id != @groupee.id
         redirect_to root_path, :notice => "You may only edit your own groupee information."
      end
   end

   #Update is the action that pushes a user to the database
   def update
      if (!current_groupee.nil? && current_groupee.id == @groupee.id)
         #This function updates the attributes of the current user if successfull, else renders edit
         if @groupee.update_attributes(params[:groupee])
            redirect_to @groupee, :notice => "Groupee field(s) successfully changed"
         else
            flash[:notice] = "There was an error in your submission"
            render "edit"
         end
      else
         redirect_to root_path, :notice => "You may only update your own groupee information."
      end
   end

   #Admin Only
   #Destroy is the action that removes a user from the database entirely.
   def destroy
      if (!current_groupee.nil? && current_groupee.admin?)
         groupee = Groupee.find_by_username(params[:id])
         #ensures that an admin can not delete another admin
         if !groupee.admin?
            groupee.destroy
            redirect_to groupees_path, :notice => "Groupee account was deleted"
         else
            redirect_to groupees_path
         end
      else
         render "shared/403"
      end
   end

   #Creates a definition called load_finduser which tries to find the user from the user table
   private
      def load_findgroupee
         #params[:id] remains fixed but find_by_id changes to username
         @groupee = Groupee.find_by_username(params[:id])
         #user_path(user)
      end
end

musicband_app/app/views/groupees/edit.html.erb
<h1 class="colorstyleh1">Edit Groupee</h1>

<%= form_for @groupee do |form| %>
   <%= render "shared/error_messages", :object => @groupee %>
   <%= render "shared/groupee_form", :object => form %>
   &nbsp;<%= link_to 'Show', groupee_path %></td>
   <%= render "shared/groupee_footer" %>
<% end %>

musicband_app/app/views/groupees/index.html.erb
<h1 class="colorstyleh1">All Groupees</h1>
<% @groupees.each do |groupee| %>
<table>
   <tr>
      <td><h2><%= link_to groupee.username, groupee %></h2></td>
         <div class="entry">
                  <td><%= link_to "Edit", [:edit, groupee] %></td>
                  <% if !groupee.admin? %>
                  <td><%= button_to "Delete", groupee, :confirm => "Are you sure?", :method => :delete %></td>
                  <% end %>
            <hr />
         </div>
    </tr>
</table>
<% end %>

musicband_app/app/views/groupees/new.html.erb
<h1 class="colorstyleh1">Sign-up</h1>
<br>
<%= form_for @groupee do |form| %>
   <%= render "shared/error_messages", :object => @groupee %>
   <%= render "shared/groupee_form", :object => form %>
   </td>
   <%= render "shared/groupee_footer" %>   
<% end %>

musicband_app/app/views/groupees/show.html.erb
<h1 class="colorstyleh1">Welcome&nbsp;<%= @groupee.first_name %>&nbsp;<%= @groupee.last_name %></h1>
<!----Displays the user information about a specific user------------> 
<br>
<div class="entry">
<table>
   <tr>
      <td>Personal Information</td>
      <% if current_groupee == @groupee %>
         <td><%= link_to "Edit", [:edit, @groupee] %></td>
      <% end %>
   </tr>
   <tr>
      <td>First Name</td>
      <td><%= @groupee.first_name %></td>
   </tr>
   <tr>
      <td>Last Name</td>
      <td><%= @groupee.last_name %></td>
   </tr>
   <tr>
      <td>Username</td>
      <td><%= @groupee.username %></td>
   </tr>
   <tr>
      <% if !current_groupee.nil? %>
         <% if current_groupee == @groupee || current_groupee.admin? %>
            <td>E-mail</td>
            <td><%= mail_to @groupee.email %></td>
         <% end %>
      <% end %>
   </tr>
</table>
</div>
<br>
<h2 class="colorstyleh2">Blogs</h2>
<!-----Reminder remove align and border from table and set in a class in the style sheet --->
   <!---This is the master bookmark for looping --->
<% @groupee.blogs.each do |blog| %>
<table>
      <tr>
         <td class="navaddspace"><%= link_to blog.title, blog %></td>
         <% if !current_groupee.nil? && current_groupee.id == @groupee.id %>
            <td class="navaddspace"><%= link_to "edit", edit_blog_path(blog) %></td>
         <% end %>
         <% if !current_groupee.nil? && current_groupee.admin? %>
            <td><%= button_to "Delete", blog, :confirm => "Are you sure?", :method => :delete %></td>
         <% end %>
         <div class="entry">
            <hr />
         </div>
      </tr>
</table>
<% end %>
<hr />
<table>
   <tr>
      <!----Only the current user can add a new bookmark to their profile--->
      <% if !current_groupee.nil? && current_groupee.id == @groupee.id %>
         <td><%= button_to 'New Blog', new_blog_path, :method => :get %></td>
      <% end %>
   </tr>
</table>
<% if !Performance.find(:all).empty? %>
<br>
<br>
<h3 class="colorstyleh3">Performances Attended</h3>
<br>
<table>
   <tr>
      <% @groupee.attendances.each do |attendance| %>
         <td><ul><li><%= link_to attendance.performance.name, performance_path(attendance.performance) %>
         <% if !current_groupee.nil? && current_groupee.admin? %>
            <%= link_to "x", groupee_attendance_path(attendance.groupee,attendance), :method => :delete %>&nbsp;
         <% end %>
         </li></ul></td>
      <% end %>
   </tr>
</table>
<br>
<table>
  <tr>
     <% if !current_groupee.nil? && current_groupee.id == @groupee.id %>
        <% if !Performance.find(:all).empty? %>
           <%= form_for :performance, :url => groupee_attendances_path(@groupee) do |form| %>
              <!---I want the route bookmark/id/taggings to work but it does not work---->
              <td><%= form.label :name %></td>
              <td><%= form.collection_select :performance_id, Performance.all, :id, :name %></td>
              <td><%= form.submit %></td>
           <% end %>
        <% end %>
     <% end %>
  </tr>
</table>
<% end %>