musicband_app/config/routes.rb
MusicbandApp::Application.routes.draw do

  resources :groupees do
     resources :attendances, :only =>[:create, :destroy]
  end

  resources :performances, :only => [:index, :show, :new, :create]
  resources :contacts, :only => [:index, :create, :destroy]
  resources :songs, :only => [:index, :show]

  resources :blogs do
     resources :comments, :only => [:create, :destroy]
  end

  match 'signup' => "groupees#new"
  match 'login' => "sessions#new"
  match 'sessions' => "sessions#create", :via => :post
  match 'logout' => "sessions#destroy", :via => :delete
  match 'contact' => "contacts#new"
  match 'about' => "public_pages#about"
  root :to => "public_pages#home"

end

musicband_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MusicbandApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="colorline">
      <a href="/"><%= image_tag 'Picture1.gif' %></a>
      <h1 class="logotextcolor">OLDE SCHOOL BAND</h1>
</div>
<div class="thinlinecolor">
<% if current_groupee %>
   <!----set link_to in front and then current_user.username inside of the user_path()--->
   Welcome <%=link_to current_groupee.username, groupee_path(current_groupee.username)%>
   <%= link_to "Logout", logout_path, :method => :delete %>
<% else %>
   <%= link_to "Login", "/login" %>
   <%= link_to "Register", "/signup" %>
<% end %>
</div>
<nav class="navcenter"><span class="navaddspace"><%= link_to "About", about_path %></span><span class="navaddspace"><%= link_to "Contact", "/contact" %></span><span class="navaddspace"><%= link_to "Blogs", blogs_path %></span><span class="navaddspace"><%= link_to "Songs", songs_path %></span><span><%= link_to "Performances", performances_path %></span></nav>
<% flash.each do |key, value| %>
   <br>
   <%= content_tag(:div, value, class: "alert alert-#{key}") %>
<% end %>
<div class="movedown"></div>
<%= yield %>

</body>
</html>